### ISSUE TITLE
Why I get the error "misaligned address" when training ?

### ISSUE THREAD

**Issue by aimreant** [n3011/Inception_v3_GoogLeNet#2]
However, I never get error like this when I train other nets like googLeNet. Here are logs:

```
F0925 14:07:56.489186 14091 math_functions.cu:79] Check failed: error == cudaSuccess (74 vs. 0)  misaligned address
*** Check failure stack trace: ***
    @     0x7f93c3722daa  (unknown)
    @     0x7f93c3722ce4  (unknown)
    @     0x7f93c37226e6  (unknown)
    @     0x7f93c3725687  (unknown)
    @     0x7f93c3ec36c8  caffe::caffe_gpu_memcpy()
    @     0x7f93c3e7e58e  caffe::SyncedMemory::to_gpu()
    @     0x7f93c3e7da39  caffe::SyncedMemory::gpu_data()
    @     0x7f93c3d2e522  caffe::Blob<>::gpu_data()
    @     0x7f93c3effe3e  caffe::BiasLayer<>::Backward_gpu()
    @     0x7f93c3f00917  caffe::ScaleLayer<>::Backward_gpu()
    @     0x7f93c3eaa097  caffe::Net<>::BackwardFromTo()
    @     0x7f93c3eaa201  caffe::Net<>::Backward()
    @     0x7f93c3e9df92  caffe::Solver<>::Step()
    @     0x7f93c3e9e849  caffe::Solver<>::Solve()
    @           0x40843e  train()
    @           0x405c8c  main
    @     0x7f93c227ff45  (unknown)
    @           0x40645d  (unknown)
    @              (nil)  (unknown)
```

I have checked my address, but nothing wrong.

**Comment by n3011** [comment]
that is the failure of memory allocation, make sure you have enough GPU memory, else reduce the batch size.

**Comment by aimreant** [comment]
@n3011 thanks, but I has 8G memory(GTX 1080), and my batch size is just 8 or 4, even 2..

**Comment by n3011** [comment]
that's a cuda problem, hopefully you are using cuda 8 with cudnn 5.

**Comment by aimreant** [comment]
@n3011 Definitly! Then should I use CUDA 7.5?

**Comment by zhisbug** [comment]
@aimreant did you figure out the problem?

**Comment by aimreant** [comment]
@zhisbug now it works, after using cuda 7.5 or latest cuda 8. But I'm not sure what the problem was.

**Comment by zimenglan-sysu-512** [comment]
@aimreant how do you solve this problem? please help. thanks.

**Comment by aimreant** [comment]
@zimenglan-sysu-512 using latest cuda 8. Hope it can help you.

**Comment by zimenglan-sysu-512** [comment]
@aimreant i use cuda 8.0 and cudnn v5, i have no idea how to fix it.

**Comment by aseuteurideu** [comment]
@zimenglan-sysu-512 
I have the same problem with my own architecture.
But one interesting thing, one of my architecture works in cuda 8.0 and cudnn v5.1 while it is not working in cuda 8.0 and cudnn v5. May be you should try upgrading the cudnn to 5.1 for your case.
It may not work also as I still got the same "misaligned address" in other architectures.

**Comment by zimenglan-sysu-512** [comment]
@kalkaneus thanks.
i will try it later.

**Comment by aseuteurideu** [comment]
@zimenglan-sysu-512 
I compile caffe without cudnn. It works for my other problems too.
The consequence is the training become slower. May be you can try this if cudnn v5.1 can't fix the problem
